# Generated by Django 5.0.6 on 2024-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('opening_dateTime', models.DateTimeField()),
                ('facebook', models.URLField()),
                ('x', models.URLField()),
                ('linkedIn', models.URLField()),
                ('Instagram', models.URLField()),
            ],
        ),
    ]
