# Generated by Django 5.0.6 on 2024-07-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='Section',
            new_name='section',
        ),
    ]
