# Generated by Django 5.0.6 on 2024-07-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_rename_section_doctors_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doctor_image',
            field=models.ImageField(default='', upload_to='appointment/'),
        ),
    ]
