# Generated by Django 5.0.6 on 2024-07-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_doctors_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='icon_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
